### ISSUE TITLE
Can I generate `prisma-client-py` with the Node `prisma` CLI?

### ISSUE THREAD

**Issue by janpio** [RobertCraigie/prisma-client-py#159]
Is there a way to use `npx prisma generate` to generate the Python client instead of using the package CLI via pip with `pip install -U prisma`?

**Comment by RobertCraigie** [comment]
It should be possible to generate the python client using `npx prisma generate` without any extra setup, does it not work for you?

It should be noted that you will have to `pip install prisma` first but there is nothing python specific in the packaged CLI.

**Comment by janpio** [comment]
I honestly did not try (as I have no `pip` locally) but only read the docs where this option was not documented.

**Comment by RobertCraigie** [comment]
Ah okay, I should explicitly document that then, it should work in theory and I think I've tried it in the past with success.

**Comment by janpio** [comment]
Considering that the pip installed CLI can not run the JS Client generation, I think that might be a valid use case (while we try to figure that out and fix it).

**Comment by RobertCraigie** [comment]
I forgot that I explicitly check the prisma version before generating, this does make it more difficult to use the Node CLI to generate the Python client but it's still possible, you just have to explicitly pass the version if the Python Client is not on the latest version, e.g.

```
npx prisma@3.4.0 generate
```

I will also improve the version check error message to include the aforementioned fix.

**Comment by RobertCraigie** [comment]
However, I did encounter https://github.com/prisma/prisma/issues/10573 while testing which makes the above workaround more difficult to use.
