### ISSUE TITLE
Add full support for filtering by relations

### ISSUE THREAD

**Issue by RobertCraigie** [RobertCraigie/prisma-client-py#17]
## Problem

Currently only support nested filtering (through the include argument), this means that even if nothing matches the nested filter the base filter still passes, which could be confusing.

## Suggested solution

Add relational fields to `WhereInput`, e.g.

```prisma
model Post {
  ...
  categories Category[] @relation(references: [id])
}

model Category {
  id    Int    @id @default(autoincrement())
  posts Post[] @relation(references: [id])
  name  String
}
```

```py
class PostWhereInput(TypedDict, total=False):
	...
	categories: Optional['CategoryListRelationalFilter']

class CategoryListRelationalFilter(TypedDict, total=False):
	every: Optional['CategoryWhereInput']
	some: Optional['CategoryWhereInput']
	none: Optional['CategoryWhereInput']
```

## Additional context

Playground schema screenshot

![](https://i.gyazo.com/313c94b72f5c5cbc1e52b260001444b9.png)

**Comment by danielweil** [comment]
Is this feature available in v0.4?

I have been trying to use relation filter in where clauses but I keep getting Field does not exist on enclosing type.` at `Query.findUniqueRole.where.RoleWhereUniqueInput.User.

I have tried it in some different ways:

![image](https://user-images.githubusercontent.com/44274213/144921694-1817859e-a85c-4613-9521-64120f710fc2.png)
![image](https://user-images.githubusercontent.com/44274213/144921737-eb2e6c91-dec2-41bb-8065-e11e8980cc9f.png)
![image](https://user-images.githubusercontent.com/44274213/144921763-0461b7c8-27b2-4a26-a93e-fca56d37b153.png)
![image](https://user-images.githubusercontent.com/44274213/144921794-fe58415a-9aec-4e79-a8b5-0c35c17c7c9a.png)

**Comment by RobertCraigie** [comment]
@danielweil You need to wrap the relational field query with either `is` or `is_not` for one-to-one relations and either `some`, `none` or `every` for one-to many / many-to-many relation.

https://prisma-client-py.readthedocs.io/en/latest/reference/operations/#filtering-by-relational-fields

In your case it should be: 
```py
role = await client.role.find_first(
    where={
        'User': {
            'email': email,
        },
    },
)
```

Also it looks like you're using VSCode, if so you should definitely install the Pylance extension which will suggest the query arguments for you when you trigger auto-complete: https://github.com/RobertCraigie/prisma-client-py/blob/main/docs/showcase.gif

**Comment by danielweil** [comment]
Thanks!

**Comment by danielweil** [comment]
Do I have to apply any setting for the autocomplete to work? Here it still doesn't show up

**Comment by RobertCraigie** [comment]
You have to manually trigger autocomplete: https://code.visualstudio.com/docs/editor/intellisense

The `Client` instance also has to be resolvable by the type checker, i.e. if you hover over it should say something like `client: Client`

**Comment by danielweil** [comment]
It does not.

![image](https://user-images.githubusercontent.com/44274213/144926211-1f825cb7-8267-41c9-9cc2-abb5bf7475e7.png)
![image](https://user-images.githubusercontent.com/44274213/144926505-01d12dcd-c4e8-486d-baa7-f4adfdb36215.png)

**Comment by danielweil** [comment]
It already is. 
![image](https://user-images.githubusercontent.com/44274213/144926985-b5159d29-7ff4-4354-b555-d3fd3d843171.png)

Can this be related to my python running in WSL?

I am writing it because I use Azure AD postgres JWT access to database.

**Comment by RobertCraigie** [comment]
The issue might be with any part of `DBClient.instance()` then, is that correctly resolved?

**Comment by danielweil** [comment]
About find_first relational query: 
It gave this error message....
![image](https://user-images.githubusercontent.com/44274213/144927332-68e5a250-9d48-4eb1-bbad-e3978a33b4c4.png)

Failed to validate the query: `Field does not exist on enclosing type.` at `Query.findFirstRole.where.RoleWhereInput.User.UserListRelationFilter.email

**Comment by RobertCraigie** [comment]
> Can this be related to my python running in WSL?

I don't think so, I've used Python with WSL before without any issues

> I am writing it because I use Azure AD postgres JWT access to database.

Ah I see, is this because you have to update the access token?

**Comment by RobertCraigie** [comment]
> Failed to validate the query: Field does not exist on enclosing type. at `Query.findFirstRole.where.RoleWhereInput.User.UserListRelationFilter.email

@danielweil  I'm so sorry I just realised I gave you the wrong query, it should be:

```py
role = await client.role.find_first(
    where={
        'User': {
			'is': {
				'email': email,
			},
        },
    },
)
```

**Comment by danielweil** [comment]
> Ah I see, is this because you have to update the access token?

Yep.

About the Client type, It is very weird why it doesn't work. Check this out!
![image](https://user-images.githubusercontent.com/44274213/144928058-2be89359-a73a-4686-86c4-4751d7cf64d6.png)

**Comment by RobertCraigie** [comment]
That is bizarre, can you share how you're importing the client please?

**Comment by danielweil** [comment]
> > Failed to validate the query: Field does not exist on enclosing type. at `Query.findFirstRole.where.RoleWhereInput.User.UserListRelationFilter.email
> 
> @danielweil I'm so sorry I just realised I gave you the wrong query, it should be:
> 
> ```python
> role = await client.role.find_first(
>     where={
>         'User': {
>             'is': {
>                 'email': email,
>             },
>         },
>     },
> )
> ```

Might be something here!

 Failed to validate the query: `Field does not exist on enclosing type.` at `Query.findFirstRole.where.RoleWhereInput.User.UserListRelationFilter.is`

**Comment by danielweil** [comment]
![image](https://user-images.githubusercontent.com/44274213/144928284-44a0cc99-7207-4609-b181-6ed3452f7486.png)


> That is bizarre, can you share how you're importing the client please?

Very

![image](https://user-images.githubusercontent.com/44274213/144928301-8a61366a-8d69-4118-a7d6-c0e066afab98.png)

**Comment by RobertCraigie** [comment]
> Failed to validate the query: Field does not exist on enclosing type. at Query.findFirstRole.where.RoleWhereInput.User.UserListRelationFilter.is

Ah sorry I missed that it was a list relation, replace `is` with `every`

**Comment by danielweil** [comment]
> > Failed to validate the query: Field does not exist on enclosing type. at Query.findFirstRole.where.RoleWhereInput.User.UserListRelationFilter.is
> 
> Ah sorry I missed that it was a list relation, replace `is` with `every`

That worked out!

**Comment by RobertCraigie** [comment]
@danielweil Glad I could help!

About the Client type, does hovering over the import resolve correctly?

**Comment by RobertCraigie** [comment]
If that does, are you overriding the Client name anywhere?

**Comment by danielweil** [comment]
It does not and I do not override it anywhere

**Comment by RobertCraigie** [comment]
That sounds like VSCode is using the wrong python interpreter then. Are you using a venv?

**Comment by RobertCraigie** [comment]
At the bottom left of your screen you should see something like this:
![e49abce59784c99292c9a54a01c6ef80](https://user-images.githubusercontent.com/23125036/144929646-8c9ec1b9-1d15-47ec-a929-d6d62ce64ca6.png)

Click on the button that says `Python ...` and select the python interpreter that you're using.

**Comment by danielweil** [comment]
I opened VSCode in a remote session and now the imports show the correct class. By my get_client method still does not. I guess it is because of the async, but I can't get it to work.

On other hand, I have another issue with upsert:

I am trying to use it as a findOrCreate idea, but something in the where clause is causing an error:
![image](https://user-images.githubusercontent.com/44274213/144932172-46a25fa2-8f5b-4bdc-ad25-51607e2afa0b.png)

Failed to validate the query: `Field does not exist on enclosing type.` at `Mutation.upsertOneUser.where.UserWhereUniqueInput.email

**Comment by RobertCraigie** [comment]
> Failed to validate the query: Field does not exist on enclosing type. at `Mutation.upsertOneUser.where.UserWhereUniqueInput.email

You need to add an `@unique` to the `email` field definition.

```prisma
model User {
  //
  email String @db.VarChar(255) @unique
  //
}
```

**Comment by danielweil** [comment]
> > Failed to validate the query: Field does not exist on enclosing type. at `Mutation.upsertOneUser.where.UserWhereUniqueInput.email
> 
> You need to add an `@unique` to the `email` field definition.
> 
> ```prisma
> model User {
>   //
>   email String @db.VarChar(255) @unique
>   //
> }
> ```

Thanks!

**Comment by RobertCraigie** [comment]
> I opened VSCode in a remote session and now the imports show the correct class. By my get_client method still does not. I guess it is because of the async, but I can't get it to work.

Do you know what doesn't work, is the `Client` return type resolved correctly?

**Comment by danielweil** [comment]
Not by my function:

![image](https://user-images.githubusercontent.com/44274213/144933162-3092c8f1-4fc7-425c-88e4-c12a1a11fc7e.png)
![image](https://user-images.githubusercontent.com/44274213/144933181-b79867a3-9804-4d33-849a-3c95e618421c.png)

![image](https://user-images.githubusercontent.com/44274213/144933200-0739a169-02be-4e3e-9999-56ac43cb8bbb.png)

How should it be with async functions in python? I tried Coroutine but failed.

**Comment by RobertCraigie** [comment]
The issue is that you've typed the `instance()` function incorrectly. It needs to be typed to return whatever class implements the `get_client()` method.

**Comment by danielweil** [comment]
Thanks! worked perfectly

**Comment by farzad-salimijazi** [comment]
> > > Failed to validate the query: Field does not exist on enclosing type. at `Query.findFirstRole.where.RoleWhereInput.User.UserListRelationFilter.email
> > 
> > 
> > @danielweil I'm so sorry I just realised I gave you the wrong query, it should be:
> > ```python
> > role = await client.role.find_first(
> >     where={
> >         'User': {
> >             'is': {
> >                 'email': email,
> >             },
> >         },
> >     },
> > )
> > ```
> 
> Might be something here!
> 
> Failed to validate the query: `Field does not exist on enclosing type.` at `Query.findFirstRole.where.RoleWhereInput.User.UserListRelationFilter.is`



> Thanks! worked perfectly

@danielweil  how did you solve this ? we tried "is", and "every" according to the documents but we can't query based on relation fields? any suggestions?

**Comment by RobertCraigie** [comment]
@farzad-salimijazi I'm sorry you're encountering difficulties, could you share your schema and the query you're trying to write so I can offer some help :)
