### ISSUE TITLE
Unable to match input value to any allowed input type for the field. Parse errors: [Query parsing/validation error at `Mutation.upsertOneUser.create.UserCreateInput.name`: Field does not exist on enclosing type., Query parsing/validation error at `Mutation.upsertOneUser.create.UserUncheckedCreateInput.name`: Field does not exist on enclosing type.]` at `Mutation.upsertOneUser.create

### ISSUE THREAD

**Issue by danielweil** [RobertCraigie/prisma-client-py#180]
Hey, hello again!

It is giving me the error message:

Unable to match input value to any allowed input type for the field. Parse errors: [Query parsing/validation error at `Mutation.upsertOneUser.create.UserCreateInput.name`: Field does not exist on enclosing type., Query parsing/validation error at `Mutation.upsertOneUser.create.UserUncheckedCreateInput.name`: Field does not exist on enclosing type.]` at `Mutation.upsertOneUser.create

when I added the field "name" into my object.

How can I fix it?

**Comment by RobertCraigie** [comment]
Can you share the Prisma Client Python query that raises that error and your Prisma Schema please?

**Comment by danielweil** [comment]
user = await client.user.upsert(
    where={'email': email},
    data={
      'create': { 'email': email, 'name': name },
      'update': {},
    },
  )

**Comment by RobertCraigie** [comment]
Are you sure that the name field exists and that the client is up to date? (i.e. run `prisma generate`)

**Comment by danielweil** [comment]
Hey, thanks! The issue is about output in the schema file. Strangely, in my local environment, If I output to another folder using the output property, this error keeps occurring. Do you know why?

**Comment by RobertCraigie** [comment]
My guess would be that you're not importing the prisma module from the custom output.

**Comment by RobertCraigie** [comment]
For example, if you have `output = "prisma2"` then in your code you must write `import prisma2` instead of `import prisma`

**Comment by danielweil** [comment]
I had output = './client'

How should I import it?

**Comment by RobertCraigie** [comment]
You should import it like:

```py
import client
```

**Comment by danielweil** [comment]
Thanks I will give it a try

**Comment by danielweil** [comment]
Did not work!  Exception: ModuleNotFoundError: No module named 'client'. Troubleshooting Guide: https://aka.ms/functions-modulenotfound

**Comment by RobertCraigie** [comment]
Because you're importing a local module you need to make sure that the directory that the module is in is in the python path.

How are you running your code and where is the python file located?
