### ISSUE TITLE
Cannot use an Enum as part of a composed ID.

### ISSUE THREAD

**Issue by danielweil** [RobertCraigie/prisma-client-py#190]
Hello,

I want to build a relation table containing three foreign keys ID's and another column containing an ENUM. As I need each row to be unique, I added a @@id containing all three ID's and the ENUM column.

When I try to start my app after generating the binaries, it gives me the following error:

![image](https://user-images.githubusercontent.com/44274213/146999460-63c3320e-6c38-4d04-8d20-1798e66e4059.png)

After looking a bit into it, I found out that types.py contains a syntax error:

![image](https://user-images.githubusercontent.com/44274213/146999484-f4fcbbd2-be83-40d1-8edf-e64aef358ddc.png)

Is this behaviour expected? Can I use all four information as ID's?

Sincerely. Thanks,

**Comment by danielweil** [comment]
Is there any way to not use the ENUM as part of the ID and make the row unique while this fix is not released?

**Comment by RobertCraigie** [comment]
@danielweil I've created a fix for this issue, can you please try it out and let me know if it fixes your issue?

```
pip install -U git+https://github.com/RobertCraigie/prisma-client-py@fix/190
```

**Comment by danielweil** [comment]
Sure! Will try it out!

**Comment by danielweil** [comment]
It worked perfectly. Can you make a new merge with the transaction branch for a wip for me?

**Comment by RobertCraigie** [comment]
Yeah of course, I've just updated the `wip/transactions` branch.

Thanks for the bug report!

**Comment by danielweil** [comment]
Excelent work!
