### ISSUE TITLE
Help with Procedures in SQLServer

### ISSUE THREAD

**Issue by danielweil** [RobertCraigie/prisma-client-py#197]
Hey,

Thanks for the amazing package. I am trying to call procedures in SQLServer but I keep getting ReadTimeout. Do you know how should I do it?

Thanks!

**Comment by danielweil** [comment]
![image](https://user-images.githubusercontent.com/44274213/147588440-57d7cf17-9ba8-4683-85ec-1b8f63affa60.png)


![image](https://user-images.githubusercontent.com/44274213/147588455-a560e78d-dd01-45e1-becb-febeecf6e0f3.png)

**Comment by RobertCraigie** [comment]
Try installing the package from GitHub and you can increase the http timeout:

```py
client = Client(
    http={
        'timeout': 20
    },
)
```

**Comment by danielweil** [comment]
I am using the WIP/transaction branch you merged for me. Is this feature available in there? I tried using connect_timeout but the error persisted.

**Comment by RobertCraigie** [comment]
Ah, sorry that feature is not available on that branch yet, sorry.

I won't be able to update that branch for at least a few hours so in the meantime you should be able to patch it like so:

```py
from httpx import AsyncClient
from prisma._async_http import HTTP

def patched_open(obj):
    obj.session = AsyncClient(timeout=15)


HTTP.open = patched_open
```

I haven't tested this so let me know if you encounter any issues.

**Comment by danielweil** [comment]
I patched it directly in the generated client and worked!

**Comment by RobertCraigie** [comment]
Good news! Are you no longer encountering `ReadTimeout` errors?

**Comment by RobertCraigie** [comment]
@danielweil I've updated the `wip/transactions` branch, you should now be able to use the original solution I proposed!
