### ISSUE TITLE
Rename `Client` to `Prisma`

### ISSUE THREAD

**Issue by RobertCraigie** [RobertCraigie/prisma-client-py#205]
## Problem

When using Prisma alongside other frameworks, it is not immediately clear what `Client` is a reference to - is it a HTTP Client? An external API Client?

## Suggested solution

We should rename the `Client` to `Prisma`, this makes it very clear. However we should also keep the `Client` name for backwards compatibility.

```py
class Prisma:
    ...

Client = Prisma
```

We should also update the documentation accordingly.

## Additional context

There is one downside to this, the python convention is to instantiate classes with the lowercase class name, e.g.

```py
prisma = Prisma()
```

As the package is also named `prisma` there could be name conflicts that arise from this.

**Comment by kivo360** [comment]
Sub, it's `ricksanchez` from Discord. I'll take this issue as my first problem.
