### ISSUE TITLE
Creating from a Superset Object

### ISSUE THREAD

**Issue by danielweil** [RobertCraigie/prisma-client-py#206]
Hey,

Is there any way to create an object from a superset object containing the desired fields but also containing other fields that are not present in the model?

Thanks!

**Comment by RobertCraigie** [comment]
@danielweil I'm not sure I understand what you mean, could you elaborate further please.

If I am understanding you correctly, this is not possible, you can only define models in the Prisma Schema and there is no inheritance supported yet.

**Comment by danielweil** [comment]
For instance,

My model Test is defined with fields "primary Int" and "secondary Int".

All I want is to create objects with await client.test.create_many(
    data=[
        {'primary': 1, 'secondary': 33, 'garbage': 3},
        {'primary': 2, 'secondary': 34, 'garbage': 3},
        {'primary': 3, 'secondary': 35, 'garbage': 3},
    ],
)
Without having to filter the dictonary for it to contain only the model's fields.

**Comment by RobertCraigie** [comment]
What do you think about doing this?

```py
data = [
    {'primary': 1, 'secondary': 33, 'garbage': 3},
    {'primary': 2, 'secondary': 34, 'garbage': 3},
    {'primary': 3, 'secondary': 35, 'garbage': 3},
]
await client.test.create_many(
    data=[
        {'primary': d['primary'], 'secondary': d['secondary']}
        for d in data
    ],
)
```

**Comment by danielweil** [comment]
I guess it is a good approach. Negatiive side of it is that I will use 24 fields. Guess it will be a bit poluted.

**Comment by RobertCraigie** [comment]
@danielweil Here's a small script to filter a dictionary to only include the fields present in the given model:

```py
from typing import Any, Dict, Type
from pydantic import BaseModel
from prisma.models import User

def filter_fields(model: Type[BaseModel], data: Dict[str, Any]) -> Dict[str, Any]:
    new = {}
    fields = model.__fields__
    for key, value in data.items():
        if key in fields:
            new[key] = value
    return new

print(filter_fields(User, {'name': 'Robert', 'garbage': 1}))
```

**Comment by danielweil** [comment]
Thanks!
