### ISSUE TITLE
Where clause with multiple values

### ISSUE THREAD

**Issue by danielweil** [RobertCraigie/prisma-client-py#208]
Hey, 

Is there any way to use IN and NOT IN for normal kind of columns in the where clause? 

Ex: Get the objects from the db from a list of IDs.

Sorry for opening an issue, I searched the docs but couldn't find it.

**Comment by RobertCraigie** [comment]
What do you mean by normal kind of columns?

**Comment by danielweil** [comment]
Integers and strings.

**Comment by RobertCraigie** [comment]
I need to improve the structure of the documentation.

You can find the documentation for these operations here: 
https://prisma-client-py.readthedocs.io/en/stable/reference/operations/#string-fields

**Comment by RobertCraigie** [comment]
May I ask where you were looking in the documentation before?

I find it difficult to know whether or not the documentation I've written is well structured so any feedback would be greatly appreciated \:)

**Comment by danielweil** [comment]
Guess it is my fault.

I passed it through the page but thought that "desc" could be ordering descenent. My Bad!

Thanks!

**Comment by RobertCraigie** [comment]
Don't worry about it, the documentation does need some work.

**Comment by RobertCraigie** [comment]
Ah I see, I should use a different field name to showcase that API.

**Comment by danielweil** [comment]
Can I ask you another doubt?

I am trying to update a foreign key in my object, and I saw previously that I had to use "connect" keywork.

I was able to make it work in create clauses, but not in update. Can you help me out?

![image](https://user-images.githubusercontent.com/44274213/148302340-06ae0b7b-b4d5-4ddc-9e1d-b2cf40eb70bc.png)

![image](https://user-images.githubusercontent.com/44274213/148302366-82ec1faa-18bb-4f38-be3f-7a4c51da638b.png)

![image](https://user-images.githubusercontent.com/44274213/148302396-3fd134c8-9cbc-4045-bed5-5a19441d8e9a.png)

**Comment by RobertCraigie** [comment]
@danielweil I think this is actually a bug, let me look into it further.

**Comment by RobertCraigie** [comment]
@danielweil You can't update a relation in an `update_many` query.

**Comment by RobertCraigie** [comment]
https://github.com/prisma/prisma/issues/3143

**Comment by danielweil** [comment]
How should go on for now?

**Comment by RobertCraigie** [comment]
You could try using query batching and switch to making multiple `update` calls instead of one `update_many`: https://prisma-client-py.readthedocs.io/en/stable/reference/batching/

However, I don't know if this will work for your use case

**Comment by danielweil** [comment]
Should raw queries work? I tried using it for the update and it gave me this error:

![image](https://user-images.githubusercontent.com/44274213/148306258-6721a2f0-960d-4f6b-aca3-3edfefc38467.png)

**Comment by RobertCraigie** [comment]
That looks like it could be a bug, Clcan you share the debug logs please?

https://prisma-client-py.readthedocs.io/en/stable/reference/logging/#debugging-the-client

**Comment by danielweil** [comment]
Thanks! I could fix the problem with the message!. Thanks
