### ISSUE TITLE
Delegate binary downloading to prisma

### ISSUE THREAD

**Issue by RobertCraigie** [RobertCraigie/prisma-client-py#22]
## Problem

With many possible configurations and settings, binary downloading is complicated, as such we should see if it is possible to delegate this task to the prisma as they already handle all of it for us.

This is an issue as we currently don't respect any binary targets options or http proxy options like prisma [does](https://www.prisma.io/docs/reference/api-reference/environment-variables-reference).

We would still have to download the CLI ourselves at the very least first.

**Comment by RobertCraigie** [comment]
@janpio Thank you! I will definitely make use of that if I start working on this.

> prisma generate can also take care of downloading and supplying the Query Engine to a generator artifact

I did notice that while reading through some prisma code and added it but don't make use of it:
https://github.com/RobertCraigie/prisma-client-py/blob/33dc2c03e1357c0bf7d34d2a321815bc605aab4c/src/prisma/jsonrpc.py#L35

**Comment by janpio** [comment]
My current understanding would be that it should pass a path to the engine, yes. But I am not aware of anyone using that, so might also be utterly broken. A quick read through the generator code on Prisma side might give clarity if this can even work.

**Comment by RobertCraigie** [comment]
You are correct it does pass the engine path to the generator.

However even though the native binaries are successfully downloaded, the following error is thrown when running `prisma generate` with and without binary targets.

```
  prisma:loadEnv skipping package.json at /package.json +0ms
  prisma:tryLoadEnv Environment variables not found at null +0ms
  prisma:tryLoadEnv Environment variables not found at undefined +1ms
  prisma:tryLoadEnv No Environment variables loaded +0ms
  prisma:engines binaries to download query-engine, migration-engine, introspection-engine, prisma-fmt +0ms
Prisma schema loaded from tests/data/schema.prisma
  plusX Execution permissions of /private/var/folders/ql/0v8h20s972s6zz4t_3qc49bc0000gp/T/prisma-binaries/query-engine-darwin are fine +0ms
  prisma:getConfig Using Query Engine Binary at: /private/var/folders/ql/0v8h20s972s6zz4t_3qc49bc0000gp/T/prisma-binaries/query-engine-darwin +0ms
  plusX Execution permissions of /private/var/folders/ql/0v8h20s972s6zz4t_3qc49bc0000gp/T/prisma-binaries/query-engine-darwin are fine +505ms
  prisma:getDMMF Using Query Engine Binary at: /private/var/folders/ql/0v8h20s972s6zz4t_3qc49bc0000gp/T/prisma-binaries/query-engine-darwin +0ms
  prisma:getGenerators neededVersions {
  "60b19f4a1de4fe95741da371b4c44a92f4d1adcb": {
    "engines": [
      "queryEngine"
    ],
    "binaryTargets": [
      {
        "fromEnvVar": null,
        "value": "darwin"
      },
      {
        "fromEnvVar": null,
        "value": "rhel-openssl-1.0.x"
      }
    ]
  }
} +0ms
  prisma:download file /snapshot/node_modules/prisma/query-engine-darwin does not exist and must be downloaded +0ms
  prisma:download file /snapshot/node_modules/prisma/query-engine-rhel-openssl-1.0.x does not exist and must be downloaded +0ms
Error: Error: File '/**/node_modules/prisma/query-engine-darwin' was not included into executable at compilation stage. Please recompile adding it as asset or script.
    at error_ENOENT (pkg/prelude/bootstrap.js:446:17)
    at readFileFromSnapshot (pkg/prelude/bootstrap.js:729:29)
    at readFile (pkg/prelude/bootstrap.js:796:5)
    at internal/util.js:297:30
    at new Promise (<anonymous>)
    at readFile (internal/util.js:296:12)
    at maybeCopyToTmp (/snapshot/node_modules/prisma/build/index.js:26765:26)
    at async download (/snapshot/node_modules/prisma/build/index.js:26562:41)
    at async getBinaryPathsByVersion (/snapshot/node_modules/prisma/build/index.js:36480:43)
    at async Object.getGenerators (/snapshot/node_modules/prisma/build/index.js:36403:36)
```

I can provide a full repro if that would help.

**Comment by janpio** [comment]
That would be neat. 

Are you using `pkg` to package the CLI? That is often a pain... (at least it is for our Go Client which does similar things) But of course there is no other real alternative.

**Comment by RobertCraigie** [comment]
Yes, I have used `pkg` before and it was not fun to say the least.

This actually uses the exact same CLI binary as the Go Client does and the engine binaries are handled in a similar way (I essentially just rewrote the Go Client's solution in python).

Here's a reproduction for the issue, it assumes you have `python3` installed.
https://github.com/RobertCraigie/prisma-reproductions/tree/main/py-22
