### ISSUE TITLE
Scalar relational fields are not included in `create_many` input

### ISSUE THREAD

**Issue by RobertCraigie** [RobertCraigie/prisma-client-py#262]
## Bug description

The following query should be supported.

```py
await client.profile.create_many(
    data=[
        {'user_id': 'a', 'description': 'Foo'},
        {'user_id': 'b', 'description': 'Foo 2'},
    ],
)
```

## How to reproduce

Run pyright on the above query

## Expected behavior

No errors

## Prisma information

Internal test schema

## Environment & setup

- OS:  Mac OS
- Database:  PostgreSQL
- Python version:  3.9.9

**Comment by nilsso** [comment]
Limitation of prisma: [When using a `connect` or `create` block in a create or update, other scalar relation fields cannot be used directly][issue].

[issue]: https://github.com/prisma/prisma/issues/7093

**Comment by nilsso** [comment]
Actually it gets a bit weirder. If mixing `"create"`/`"connect"` with scalars always failed then a lot more queries would fail. It seems that field attributes like `@default(autoincrement)` are the cause of the failure within prisma when mixing.

Given the schema
```prisma
model A {
    id Int @id @default(autoincrement())

    Bs B[]
}

model B {
    id Int @id // @default(autoincrement())

    aId Int
    a A @relation(fields: [aId], references: [id])
}
```
And the query
```python
a = await prisma.a.create(data={})
await prisma.b.create(
    data=data,
)
```

The following `data` values run fine
```python
data={
    "id": 5,
    "aId": a.id,
}
```
```python
# important!
data={
    "id": 5,
    "a": {
        "connect": {
            "id": a.id,
        },
    },
}
```

But with `B.id` attributed with `@default(autoincrement())`, these work
```python
data={
    "aId": a.id,
}
```
```python
data={
    "id": 5,
    "aId": a.id,
}
```
```python
data={
    "a": {
        "connect": {
            "id": a.id,
        },
    },
}
```

While this one *does not*
```python
# important!
data={
    "id": 5,
    "a": {
        "connect": {
            "id": a.id,
        },
    },
}
```
```
prisma.errors.MissingRequiredValueError: Failed to validate the query: `Unable to match input value to any allowed input type for the field. Parse errors: [Query parsing/validation error at `Mutation.createOneB.data.BCreateInput.id`: Field does not exist on enclosing type., Query parsing/validation error at `Mutation.createOneB.data.BUncheckedCreateInput.aId`: A value is required but not set.]` at `Mutation.createOneB.data`
```

**Comment by RobertCraigie** [comment]
Thank you for the very detailed investigation!

As a short term fix I'm thinking of just adding those scalar relational fields to the create input and making them optional even if the relation is required to exist.

As I mentioned earlier the difficulty with this is defining the `TypedDict` such that either the scalar relational field is required or the nested form `connect` / `create` etc. I think this is doable but it would mean that we would have to generate different `TypedDict`s for each case, i.e. one for the scalar field(s) and one for the nested form. That then gets even more complicated when you have multiple relations on the same model as we would have to generate a TypedDict for every possible permutation of inputs, e.g. `{"a_id" 1, "b_id": 2}`, `{"a_id": 1, "b": {"connect": {"id": 2}}}`, `{"a": {"connect": {"id": 1}}, "b_id": 2}` and so on.
