### ISSUE TITLE
Postgres JSONB operators seem to misbehave in query_raw prepared statements.

### ISSUE THREAD

**Issue by anthonylobko** [RobertCraigie/prisma-client-py#279]
## Bug description

Postgres jsonb operators (namely ->>) don't seem to behave correctly with prepared statements when using query_raw.

## How to reproduce

1. Have a JSONB field on a table in postgres
2. Attempt to do a raw query 
`client.query_raw('''select * from tbl where columnname ->> 'somefield' = ?''', 'a value')`
3. See an error produced "db error: ERROR: syntax error at end of input". Quoting around the ? doesn't help either (single or double).  
4. If you explicitly put the value in there, it does behave correctly (so `client.query_raw('''select * from tbl where columnname ->> 'somefield' = 'a value'''')` works fine)

## Expected behavior

This jsonb query should work fine?

## Environment & setup

- OS: MacOS
- Database: PostgreSQL 13
- Python version: 3.10.2
- Prisma version: 0.5.0

```

```

**Comment by RobertCraigie** [comment]
@anthonylobko Using `$1` instead of `?` works for me. Is `?` supported syntax?

```py
results = await client.query_raw(
    '''select * from public."Types" where "jsonb" ->> 'somefield' = $1''', 'a_value'
)
```

**Comment by anthonylobko** [comment]
> @anthonylobko Using `$1` instead of `?` works for me. Is `?` supported syntax?
> 
> ```python
> results = await client.query_raw(
>     '''select * from public."Types" where "jsonb" ->> 'somefield' = $1''', 'a_value'
> )
> ```

It is in other tools, however, in this case, I was following the documentation https://prisma-client-py.readthedocs.io/en/stable/reference/operations/#raw-queries so I assumed that it was valid. There's a few places in the docs this is used incorrectly if this wasn't meant to be valid.

**Comment by RobertCraigie** [comment]
@anthonylobko Sorry about that I should've been more clear in the docs.

You need to use the parameter syntax specific to your database provider. In the docs we use the SQLite method as an example but in your case as you're using PostgreSQL you need to use their specific syntax which is `$N`.
