### ISSUE TITLE
Add support for Json and filtering by Json

### ISSUE THREAD

**Issue by RobertCraigie** [RobertCraigie/prisma-client-py#29]
## Problem

Since [v2.23.0](https://github.com/prisma/prisma/releases/tag/2.23.0), Prisma has had experimental support for filtering by Json, we should officially support the Json type and filtering by it.

## Suggested Solution

Due to limitations with our query builder we will not be able to serialize json values correctly as they are treated like any other field type. We could get it working by naively checking field types and adding special handling for `Json` fields however I don't like this.

Create a new python type `Json` that must be used to encapsulate any json data, e.g.

```py
from prisma import Json

user = await client.user.create(
    data={
        'name': 'Robert',
        'meta': Json(country='Scotland')
    },
)
user = await client.user.create(
    data={
        'name': 'Robert',
        'meta': Json(['foo', 'wow'])
    },
)
```

Something like:

```py
class Json:
    @overload
    def __init__(self, **kwargs: Serializable) -> None:
        ...
    
    @overload
    def __init__(self, data: Serializable) -> None:
        ...
```

There is another problem with this however, pydantic supports [json types](https://pydantic-docs.helpmanual.io/usage/types/#json-type) which would make working with the returned data much easier.

**Comment by diramazioni** [comment]
Can this be documented? I've just spent the last 3 hours searching around
