### ISSUE TITLE
Add support for ScyllaDB / Cassandra

### ISSUE THREAD

**Issue by PeterCorless** [RobertCraigie/prisma-client-py#292]
## Problem

Currently doesn't have support for wide column databases like ScyllaDB and Cassandra

## Suggested solution

Add support for ScyllaDB / Cassandra a la [Catalytic ORM for Rust](https://www.scylladb.com/2022/02/15/introducing-catalytic-an-orm-designed-for-scylladb-and-cassandra-written-in-rust/)

## Alternatives

Accept no substitute!

## Additional context

q.v. [ScyllaDB Python Driver](https://python-driver.docs.scylladb.com/stable/)

**Comment by RobertCraigie** [comment]
Hey @PeterCorless, the database drivers are not actually implemented in this project. Please add a 👍 or include your use case in the corresponding issue in the Prisma repository: https://github.com/prisma/prisma/issues/2879.

Thanks!

**Comment by PeterCorless** [comment]
Thanks!
