### ISSUE TITLE
i need to use with postgres type (geometry , interval )

### ISSUE THREAD

**Issue by blackbullx16** [RobertCraigie/prisma-client-py#347]

**Comment by RobertCraigie** [comment]
Prisma doesn't support these types yet unfortunately, you'll have to use raw SQL queries if you want to use these types.

Feel free to add a thumbs up / comment your use case to the corresponding Prisma feature request: https://github.com/prisma/prisma/issues/2789

If you need help using these types with raw SQL feel free to ping me or join the community discord server :)
