### ISSUE TITLE
Access to absolute path of schema file through client

### ISSUE THREAD

**Issue by TheOnlyWayUp** [RobertCraigie/prisma-client-py#400]
## Problem

I want to locate the schema file my client is basing itself upon through the client, enabling me to find the absolute path of the schema.prisma file through python without much hassle. This would make debugging easier.

## Suggested solution

A function that returns the a path object pointing to the schema.prisma file the client is using.

## Alternatives

I'm not too sure, the generator could as well store the schema path in an environment variable while generation is occuring.

## Additional context

My actual problem isn't related to the client, but adding it would ease debugging. My libraries need to find a config file stored in the same directory as the schema, and prisma is my only dependency that generates a client based on a file, so my first thought was to see if prisma had such a function. (I can't use an absolute path because in production, it could be installed to either a global namespace or a virtual one, so i can't bank on knowing where my libraries will be)

Thanks for the good work Robert, I'm loving this client, it's my go to database solution for any project that needs one

**Comment by RobertCraigie** [comment]
This will be included in the next release:

```py
from prisma import SCHEMA_PATH

print(SCHEMA_PATH)  # Path('/absolute/path/prisma/schema.prisma')
```

**Comment by TheOnlyWayUp** [comment]
@RobertCraigie Might be a bug, 
```json
{
    "is_panic": false,
    "message": "\u001b[1;91merror\u001b[0m: \u001b[1mEnvironment variable not found: POSTGRES_DATABASE_URL.\u001b[0m\n  \u001b[1;94m-->\u001b[0m  \u001b[4mschema.prisma:4\u001b[0m\n\u001b[1;94m   | \u001b[0m\n\u001b[1;94m 3 | \u001b[0m    provider = \"postgresql\"\n\u001b[1;94m 4 | \u001b[0m    url      = \u001b[1;91menv(\"POSTGRES_DATABASE_URL\")\u001b[0m\n\u001b[1;94m   | \u001b[0m\n\nValidation Error Count: 1",
    "meta": {
        "full_error": "\u001b[1;91merror\u001b[0m: \u001b[1mEnvironment variable not found: POSTGRES_DATABASE_URL.\u001b[0m\n  \u001b[1;94m-->\u001b[0m  \u001b[4mschema.prisma:4\u001b[0m\n\u001b[1;94m   | \u001b[0m\n\u001b[1;94m 3 | \u001b[0m    provider = \"postgresql\"\n\u001b[1;94m 4 | \u001b[0m    url      = \u001b[1;91menv(\"POSTGRES_DATABASE_URL\")\u001b[0m\n\u001b[1;94m   | \u001b[0m\n\nValidation Error Count: 1"
    },
    "error_code": "P1012"
}
```
This happens when I CD into a directory and run my scripts, 
```tree
├── database_handler
│   ├── database_handler
│   │   ├── __init__.py
│   │   └── main.py
│   └── setup.py
├── prisma
│   └── schema.prisma
├── README.md
├── .env
└── temp
    ├── test_packages
    │   ├── add_fake_data.py
    │   ├── get_server.py
    │   └── __init__.py
    └── use.py
```
When I CD into the `temp` directory and run `use.py`, I get an error, whereas when I run it from the root directory (parent directory of `temp`), I don't get the error.

This isn't a bug relating to the schema file's position, but a bug regarding where Prisma reads `.env` from. In my opinion, Prisma should be reading `.env` files in the root directory, ie, `SCHEMA_PATH.parent / ".env"` , instead of making it relative to where Prisma is being imported and run from.

To make that more concise, Prisma shouldn't search for .env files based on CWD, rather, the parent directory of the `prisma` folder.

**Comment by RobertCraigie** [comment]
@TheOnlyWayUp Sorry I'm only just seeing this.

Yeah that proposed behaviour makes a lot of sense. Ultimately it's tied to the internal behaviour of the Prisma CLI as any mismatch between the client and the CLI could result in very confusing errors.

Do you know if that is how the CLI behaves?
