### ISSUE TITLE
Add option to disable .env load

### ISSUE THREAD

**Issue by iddan** [RobertCraigie/prisma-client-py#420]
## Problem

Currently, .env files are loaded by default and if the behaviour is desired to be disabled it is needed to be defined in every instance of `Prisma`.
In many production systems, it is not desired to load environment variables from .env files.

## Suggested solution

Add environment variable to disable the behaviour

## Alternatives

Change the default to not load .env

## Additional context

When loading the .env in my project `Prisma` overridden the environment variable I had already set for `DATABAE_URL` (which seems like a bug on its own)

**Comment by RobertCraigie** [comment]
This seems reasonable but I'm curious, what's your use case for having multiple `Prisma` instances at once? For individual instances you can pass the `use_dotenv` argument, for example:

```py
Prisma(use_dotenv=False)
```

If I do decide to implement this what do you think the environment variable should be named?

> When loading the .env in my project Prisma overridden the environment variable I had already set for DATABAE_URL (which seems like a bug on its own)

Yeah this is something I haven't been that happy with but it should be pretty easy to fix.

**Comment by iddan** [comment]
Thank you for your response.
> If I do decide to implement this what do you think the environment variable should be named?
I think something like: `PRISMA_LOAD_DOTENV=0|1` would make sense

**Comment by RobertCraigie** [comment]
@iddan I actually think I am not going to support this behaviour as it will not be supported by the Prisma CLI which would cause some confusion.

I do not see a strong use case for this as in the standard case it will be a simple one line change and I am also not aware of a use case for creating multiple `Prisma` instances but even in this case it is easy for the library user to make this change themselves by doing something like this:

```py
shared_config = {'use_dotenv': False)
prisma1 = Prisma(**shared_config)
prisma2 = Prisma(**shared_config)
```

I agree that overriding the already set env variables was not a good decision, I'll open another issue to track that.
