### ISSUE TITLE
Prisma Client for python is not generating.

### ISSUE THREAD

**Issue by MK272008** [RobertCraigie/prisma-client-py#425]
## Bug description

Whenever I try to generate the client using `prisma generate`, I get the following output:
```
Environment variables loaded from .env
Prisma schema loaded from schema.prisma
```

But when I try to run my code (which obviously uses the prisma client, I get the following error:
```
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Heavy Programming\Projects\The YPS Central\the-yps-central\server\__main__.py", line 2, in <module>
    from prisma import Prisma, register, get_client
  File "<frozen importlib._bootstrap>", line 1055, in _handle_fromlist
  File "D:\Heavy Programming\Projects\The YPS Central\the-yps-central\server\venv\lib\site-packages\prisma\__init__.py", line 42, in __getattr__
    raise RuntimeError(
RuntimeError: The Client hasn't been generated yet, you must run `prisma generate` before you can use the client.
See https://prisma-client-py.readthedocs.io/en/stable/reference/troubleshooting/#client-has-not-been-generated-yet
```

## How to reproduce
1. Run `prisma generate`
2. Run your code

## Expected behavior

I expected my python flask server to start successfully.

## Prisma information

```
generator client {
  provider = "prisma-client-py"
  interface = "async"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

enum Role {
  USER
  ADMIN
}

model User {
  id Int @id @default(autoincrement())
  createdAt DateTime @default(now())
  email String @unique
  username String
  firstName String
  lastName String
  role Role @default(USER)
  password String
}
```

## Environment & setup

- OS: Windows
- Database: PostgreSQL
- Python version: 3.9.10
- Prisma version: 3.13.0

**Comment by RobertCraigie** [comment]
Hi @MK272008, the issue you're experiencing is due to https://github.com/prisma/prisma/issues/10270. That issue leads to the Prisma CLI not printing the Python client's error message.

Please try running `prisma generate` again after setting the following environment variables:
- `DEBUG` to `*`
- `PRISMA_PY_DEBUG` to `1`

Let me know what the error message is and I'll investigate further.

**Comment by MK272008** [comment]
Its still not working. Just getting the same error message while running the server.

**Comment by RobertCraigie** [comment]
@MK272008 what happens when you run `prisma generate` after setting those environment variables?

**Comment by MK272008** [comment]
I only get these two lines in the terminal.
```
```

**Comment by RobertCraigie** [comment]
@MK272008 I'm not sure why you're still not getting error logs, sorry about that.

The error you're encountering is because of a typo in the `interface` option, you need to use `asyncio` instead of `async`. For example:

```prisma
generator client {
  provider  = "prisma-client-py"
  interface = "asyncio"
}
```

Please re-open if you need any more guidance :)

**Comment by jareducherek** [comment]
@RobertCraigie This is still happening with my environment. I am not getting any error messages when running `prisma migrate` with the debug options on.

```
(plutus) C:\Users\jared\Documents\Github\Personal\plutus>prisma migrate
[DEBUG  ] prisma.binaries.binaries: query-engine cached at C:\Users\jared\AppData\Local\Temp\prisma\binaries\engines\efdf9b1183dddfd4258cd181a72125755215ab7b\prisma-query-engine-windows.exe
[DEBUG  ] prisma.binaries.binaries: migration-engine cached at C:\Users\jared\AppData\Local\Temp\prisma\binaries\engines\efdf9b1183dddfd4258cd181a72125755215ab7b\prisma-migration-engine-windows.exe
[DEBUG  ] prisma.binaries.binaries: introspection-engine cached at C:\Users\jared\AppData\Local\Temp\prisma\binaries\engines\efdf9b1183dddfd4258cd181a72125755215ab7b\prisma-introspection-engine-windows.exe
[DEBUG  ] prisma.binaries.binaries: prisma-fmt cached at C:\Users\jared\AppData\Local\Temp\prisma\binaries\engines\efdf9b1183dddfd4258cd181a72125755215ab7b\prisma-prisma-fmt-windows.exe
[DEBUG  ] prisma.binaries.binaries: prisma-cli-windows.exe cached at C:\Users\jared\AppData\Local\Temp\prisma\binaries\engines\efdf9b1183dddfd4258cd181a72125755215ab7b\prisma-cli-windows.exe
[DEBUG  ] prisma.binaries.binaries: All binaries are cached
[DEBUG  ] prisma.cli.prisma: Using Prisma CLI at C:\Users\jared\AppData\Local\Temp\prisma\binaries\engines\efdf9b1183dddfd4258cd181a72125755215ab7b\prisma-cli-windows.exe
[DEBUG  ] prisma.cli.prisma: Running prisma command with args: ['migrate']
  prisma:engines binaries to download query-engine, migration-engine, introspection-engine, prisma-fmt +0ms
  prisma:download Using env var PRISMA_QUERY_ENGINE_BINARY for binary query-engine, which points to C:\Users\jared\AppData\Local\Temp\prisma\binaries\engines\efdf9b1183dddfd4258cd181a72125755215ab7b\prisma-query-engine-windows.exe +0ms
  prisma:download Using env var PRISMA_MIGRATION_ENGINE_BINARY for binary migration-engine, which points to C:\Users\jared\AppData\Local\Temp\prisma\binaries\engines\efdf9b1183dddfd4258cd181a72125755215ab7b\prisma-migration-engine-windows.exe +0ms
  prisma:download Using env var PRISMA_INTROSPECTION_ENGINE_BINARY for binary introspection-engine, which points to C:\Users\jared\AppData\Local\Temp\prisma\binaries\engines\efdf9b1183dddfd4258cd181a72125755215ab7b\prisma-introspection-engine-windows.exe +1ms
  prisma:download Using env var PRISMA_FMT_BINARY for binary prisma-fmt, which points to C:\Users\jared\AppData\Local\Temp\prisma\binaries\engines\efdf9b1183dddfd4258cd181a72125755215ab7b\prisma-prisma-fmt-windows.exe +0ms

Update the database schema with migrations

Usage

  $ prisma migrate [command] [options]

Commands for development

         dev   Create a migration from changes in Prisma schema, apply it to the database
               trigger generators (e.g. Prisma Client)
       reset   Reset your database and apply all migrations, all data will be lost

Commands for production/staging

      deploy   Apply pending migrations to the database
      status   Check the status of your database migrations
     resolve   Resolve issues with database migrations, i.e. baseline, failed migration, hotfix

Command for any stage

        diff   Compare the database schema from two arbitrary sources

Options

  -h, --help   Display this help message
    --schema   Custom path to your Prisma schema

Examples

  Create a migration from changes in Prisma schema, apply it to the database, trigger generators (e.g. Prisma Client)
  $ prisma migrate dev

  Reset your database and apply all migrations
  $ prisma migrate reset

  Apply pending migrations to the database in production/staging
  $ prisma migrate deploy

  Check the status of migrations in the production/staging database
  $ prisma migrate status

  Specify a schema
  $ prisma migrate status --schema=./schema.prisma

  Compare the database schema from two databases and render the diff as a SQL script
  $ prisma migrate diff \
    --from-url "$DATABASE_URL" \
    --to-url "postgresql://login:password@localhost:5432/db" \
    --script

  prisma:getConfig Using CLI Query Engine (Binary) at: C:\Users\jared\AppData\Local\Temp\prisma\binaries\engines\efdf9b1183dddfd4258cd181a72125755215ab7b\prisma-query-engine-windows.exe +0ms
```

**Comment by jareducherek** [comment]
@RobertCraigie This is still happening to me. I get no error messages when running `prisma generate` with this as my schema.prisma file:

```
datasource db {
  url      = env("DATABASE_URL")
  provider = "postgresql"
}

generator client {
  provider = "prisma-client-py"
  generator = "asyncio"
  recursive_type_depth = 5
}

model User {
  id        Int      @id @default(autoincrement())
  createdAt DateTime @default(now())
  email     String   @unique
  name      String?
  role      Role     @default(USER)
}

enum Role {
  USER
  ADMIN
}
```
When running `prisma db push` I get success message:
```
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Datasource "db": PostgreSQL database "plutus", schema "public" at "localhost:5432"

The database is already in sync with the Prisma schema.

Running generate... - Prisma Client Python (v0.7.0)
```

But the main.py file gives the error `The Client hasn't been generated yet, you must run `prisma generate` before you can use the client.`
```
import asyncio
from prisma import Prisma


async def main() -> None:
    db = Prisma()
    await db.connect()

    post = await db.user.create(
        {
            'email': 'test@email.com!',
            'name': 'Prisma test, databases made easy.',
        }
    )
    print(f'created post: {post.json(indent=2, sort_keys=True)}')

    found = await db.post.find_unique(where={'id': post.id})
    assert found is not None
    print(f'found post: {found.json(indent=2, sort_keys=True)}')

    await db.disconnect()


if __name__ == '__main__':
    asyncio.run(main())
```

**Comment by RobertCraigie** [comment]
@jareducherek It looks like you have `generator = "asyncio"` when you need to use `interface = "asyncio"` instead, that might be what is causing the issue.

In regards to no error message being shown, that issue will be fixed in the next release, if you want to try it out now you can install from GitHub using this command :)

```sh
pip install -U git+https://github.com/RobertCraigie/prisma-client-py
```

**Comment by jareducherek** [comment]
Thanks for the quick reply, such a simple fix! Really looking forward to digging in here, this is my first time making a database, and planning for it to be quite extensive.

**Comment by RobertCraigie** [comment]
Glad I could help!

Exciting stuff! I'm happy you chose to use Prisma for your first time working with a database and please let me know if you need any assistance :)

**Comment by Badetuch** [comment]
Hi, I've got a similar issue. 
When running my code I get the following error:

`Traceback (most recent call last):
  File "D:\Users\badet\Desktop\cloudbot\main.py", line 9, in <module>
    from prisma import Prisma
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "D:\Users\badet\PycharmProjects\1\venv\lib\site-packages\prisma\__init__.py", line 50, in __getattr__
    raise RuntimeError(
RuntimeError: The Client hasn't been generated yet, you must run `prisma generate` before you can use the client.
See https://prisma-client-py.readthedocs.io/en/stable/reference/troubleshooting/#client-has-not-been-generated-yet

Process finished with exit code 1`

My schema.prisma:

`datasource db {
  provider          = "postgresql"
  url               = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-py"
  recursive_type_depth = 5
  interface  = "asyncio"
}

model users {
  id            Int     @id @default(autoincrement())
  uid           String
  createdAt     DateTime @default(now())
  nickname      String
  trustfactor   Int
}
`

My main.py:

`import datetime
import os

from termcolor import colored
import ts3
import mariadb
import sys
import asyncio
from prisma import Prisma
from prisma import Client


# Initialize Prisma client
prisma = Client()

# Authenticate your bot with Prisma
bot_email = "hello@badespeak.net"  # Replace with your bot's email address
bot_password = "GnbacoapJQ5MQ43#"   # Replace with your bot's password

# Assuming you have a User model in your Prisma schema
authenticated_bot = prisma.user.find_first(where={"email": bot_email, "password": bot_password})

if authenticated_bot:
    bot_id = authenticated_bot.id
    print(f"Bot authenticated with ID: {bot_id}")`

However, when running 'prisma generate' I get 0 errors:
`Environment variables loaded from .env
Prisma schema loaded from schema.prisma

✔ Generated Prisma Client Python (v0.11.0) to .\venv\lib\site-packages\prisma in 134ms
`
