### ISSUE TITLE
Generator errors are not logged on windows

### ISSUE THREAD

**Issue by zznty** [RobertCraigie/prisma-client-py#449]
## Bug description

If there is some errors in generation process they wont be logged unless i set `DEBUG=*`
But [this](https://user-images.githubusercontent.com/94796179/181196127-5e217569-4a33-44df-8488-d19e95a8be0e.png) happens for me only on windows, with ubuntu wsl error being [properly logged](https://user-images.githubusercontent.com/94796179/181196419-ae5724d4-34f2-48f2-91f5-83e24ba5984e.png)

## How to reproduce

1. create model with field name that shadows python keyword (e.g `from`)
2. run `prisma generate` on windows and you will get only [two lines](https://user-images.githubusercontent.com/94796179/181196127-5e217569-4a33-44df-8488-d19e95a8be0e.png)
3. run the same command on ubuntu wsl and get [error](https://user-images.githubusercontent.com/94796179/181196419-ae5724d4-34f2-48f2-91f5-83e24ba5984e.png)

## Expected behavior

I would like to see same behavior for all platforms

## Prisma information

```prisma
model Mail {
  id   Int    @id
  from String
}
```

## Environment & setup

- OS:  Windows 11 Pro x86_64 / Ubuntu 20.04.4 LTS on Windows 11 x86_64
- Database:  PostgreSQL
- Python version:  3.10 on both
- Prisma version:

```
prisma               : 3.13.0
prisma client python : 0.6.6
platform             : windows / debian-openssl-1.1.x
engines              : efdf9b1183dddfd4258cd181a72125755215ab7b
```

**Comment by RobertCraigie** [comment]
Hey @zznty, unfortunately this is a known issue, see https://github.com/prisma/prisma/issues/10270.

As this is an error on Prisma's side, I'm not sure if there's anything I can do to fix this. In the meantime you should be able to see the output when you enable debug logging, see https://prisma-client-py.readthedocs.io/en/latest/reference/logging/.
