### ISSUE TITLE
Why is the binary download required everytime?

### ISSUE THREAD

**Issue by max-programming** [RobertCraigie/prisma-client-py#453]
### Question

I just noticed that whenever I start my app, it errors out because the prisma binaries are not installed. Why are they required to be downloaded every single time? Or can it be fixed?

**Comment by RobertCraigie** [comment]
What do you mean by every time? The binaries are currently downloaded to a `/tmp` directory which will be cleared every time you reboot your system. Until you reboot, the binaries should be cached.

**Comment by max-programming** [comment]
Alright got it @RobertCraigie 

Whenever I boot into my system, it starts downloading the binaries again. 

Now I will install the latest GitHub version of it
