### ISSUE TITLE
feat: cockroachdb support

### ISSUE THREAD

**Issue by Mokto** [RobertCraigie/prisma-client-py#459]
## Problem

Right now we can't use providers that have been added recently : Cockroachdb & Planetscale.

Any file generation attempt returns:
```
Error: Get config: Schema Parsing P1012

error: Datasource provider not known: "cockroachdb".
  -->  schema.prisma:2
   | 
 1 | datasource db {
 2 |   provider = "cockroachdb"
   | 

Validation Error Count: 1
```

## Suggested solution

Support it

Thanks a lot !

**Comment by RobertCraigie** [comment]
Hey! I'm closing this issue as I've added tests for CockroachDB to our internal test suite to ensure it is usable with Prisma Client Python. You can use CockroachDB by setting `provider` to `postgresql`.

Explicitly setting `cockroachdb` as the datasource provider still isn't explicitly supported yet, although it will be in the next release!
