### ISSUE TITLE
Argument list too long when connecting to a database with a large schema

### ISSUE THREAD

**Issue by jpbluteau** [RobertCraigie/prisma-client-py#486]
## Bug description

The query engine cannot spawn the query engine child process when the schema is too large.

The error is coming from that line https://github.com/RobertCraigie/prisma-client-py/blob/main/src/prisma/generator/templates/engine/query.py.jinja#L106.  When the schema is too large, it's content will be truncated by the OS and the engine will fail to start.  The following patch will circumvent the issue by passing the path to the schema instead of it's content:

```
env = os.environ.copy()
env.update(
    #  PRISMA_DML=self.dml,
    RUST_LOG='error',
    RUST_LOG_FORMAT='json',
    PRISMA_CLIENT_ENGINE_TYPE='binary',
 )

if os.environ.get('PRISMA_DML_PATH'):
    env.update(PRISMA_DML_PATH=os.environ.get('PRISMA_DML_PATH'))
else:
    env.update(PRISMA_DML=self.dml)
```

## How to reproduce

1. Generate a prisma.schema file with a large number of tables and fields
2. Generate the prisma client
3. Connect to the database
4. See error:

```
Traceback (most recent call last):
  File "...", line 239, in <module>
    app = CashflowLoader(args.process_date)
  File "...", line 35, in __init__
    self.db.connect()
  File ".../venv/lib/python3.9/site-packages/prisma/client.py", line 3657, in connect
    self.__engine.connect(
  File ".../venv/lib/python3.9/site-packages/prisma/engine/query.py", line 110, in connect
    self.spawn(file, timeout=timeout, datasources=datasources)
  File ".../venv/lib/python3.9/site-packages/prisma/engine/query.py", line 152, in spawn
    self.process = subprocess.Popen(
  File ".../lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File ".../lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 7] Argument list too long: '/tmp/prisma/binaries/engines/efdf9b1183dddfd4258cd181a72125755215ab7b/prisma-query-engine-debian-openssl-1.1.x'
```

## Expected behavior

No error should be reported and the connexion should be established with the database.

## Prisma information

Create a large schema file
No specific queries required

## Environment & setup

- OS: Windows 11, Ubuntu 20.10
- Database: MariaDB
- Python version: 3.9.7
- Prisma version:

```
prisma               : 3.13.0
prisma client python : 0.6.6
platform             : debian-openssl-1.1.x
engines              : efdf9b1183dddfd4258cd181a72125755215ab7b
install path         : /mnt/c/Users/andrew/OneDrive/Git_Repos/e22/Benzaiten_repos/benzaiten-processes/venv/lib/python3.9/site-packages/prisma
installed extras     : []
```

**Comment by RobertCraigie** [comment]
Hey @jpbluteau, thanks for the bug report!

I'm struggling to reproduce this myself but your suggestion of passing the Prisma Schema path to the query engine is a good solution regardless. I'm working on a fix.
