### ISSUE TITLE
Add support for transactions

### ISSUE THREAD

**Issue by RobertCraigie** [RobertCraigie/prisma-client-py#53]
Prisma has preview support for [interactive transactions](https://www.prisma.io/docs/concepts/components/prisma-client/transactions#interactive-transactions).

The base work for this has already been done in the `wip/transactions` branch, some kinks need to be ironed out.

## Status

- [x] Model-based access support
- [ ] Protect against namespace collision

### Model-based access

We could refactor the internal strategy to register and retrieve clients to use contextvars. However we should only use contextvars for transactions as otherwise it would break certain async use cases like the `python -m asyncio` REPL.

**Comment by danielweil** [comment]
Is this still a work on progress?

**Comment by RobertCraigie** [comment]
Yes this is still a work in progress, I'll update the WIP to the latest version and then you can try it out!

**Comment by danielweil** [comment]
Thanks!

**Comment by RobertCraigie** [comment]
@danielweil Just updated my WIP, you can try it out in your project by installing from the branch like so:

```
pip install -U git+https://github.com/RobertCraigie/prisma-client-py@wip/transactions
```

However, there are absolutely no guarantees this will actually work.

**Comment by danielweil** [comment]
Thanks, will try it out.

**Comment by RobertCraigie** [comment]
Let me know if you encounter any issues!

**Comment by danielweil** [comment]
I tried installing it with the command, without uninstalling my latest prisma version. It resulted in the error below:

![image](https://user-images.githubusercontent.com/44274213/146831998-0b4c3186-77b2-418c-a7f4-56b6fe5929aa.png)

**Comment by RobertCraigie** [comment]
I've never encountered that error before but it looks like it has something to do with setuptools.

Try running:

```
pip install -U pip
pip install -U setuptools
```

And then try again

**Comment by danielweil** [comment]
Worked by adding --no-use-pep517 to the pip command.

**Comment by danielweil** [comment]
Is there any docs commenting on how to use transactions? Or it is the same syntax as TS?

**Comment by RobertCraigie** [comment]
No docs yet, basically the same syntax as batching, here's an example:

```py
async with client.tx() as transaction:
    user = await transaction.user.create({'name': 'Robert'})
```

**Comment by RobertCraigie** [comment]
You can have a look through the tests for more examples:

https://github.com/RobertCraigie/prisma-client-py/blob/wip/transactions/tests/test_transactions.py

**Comment by danielweil** [comment]
Thanks! I am facing an issue here, can you thing about it? 

I use output in the schema file and outputs to '.client'. WIth version 0.2.2, my module is being added correctly and it works importing it like this:

"from prisma.client import Client"

When I use the transaction version, after generating the client, it gives me the error:

 Exception: ModuleNotFoundError: No module named 'prisma.client'. Troubleshooting Guide: https://aka.ms/functions-modulenotfound

Do you think there is something about it?

**Comment by RobertCraigie** [comment]
Are you sure you need to use a custom output in the first place? By default Prisma Client Python will generate itself to the same place it was installed to.

If you're importing from a custom output of './client' then you're going to need to import it like this:

```py
from client import Client
```

**Comment by danielweil** [comment]
It outputs to:

 Generated Prisma Client Python to ./prisma/client in 961ms

Sorry, trying to figure out here how to do it

**Comment by RobertCraigie** [comment]
Why are you using custom output?

You probably want to either remove custom output or change it to `../client`.

**Comment by RobertCraigie** [comment]
@danielweil Have you added the preview feature flag to your schema? e.g.

```prisma
generator client {
  provider               = "prisma-client-py"
  recursive_type_depth   = -1
  previewFeatures        = ["interactiveTransactions"]
}
```

**Comment by danielweil** [comment]
Robert, would you mind making a new branch where this work in progress in merged with the newest release?

**Comment by RobertCraigie** [comment]
@danielweil I've updated the `wip/transactions` branch to include the changes from the latest release.

**Comment by RobertCraigie** [comment]
@danigosa Done 👍

**Comment by RobertCraigie** [comment]
@danigosa Thanks for the detailed comment!

> Do you expect or consider to use TransactionManager out of a purely context manager?

Yes, I imagine that there may be cases where using a context manager is awkward but I can't think of any specific examples off the top of my head.

> Why the TransactionManager.__aexit__() do not call rollback when error?

That appears to be a complete oversight on my part, thanks for pointing that out! While implementing this feature I was focused on getting the interactions with the engine to work instead of the actual feature behaviour. I'm grateful this was still a WIP as that is a pretty big oversight...

> Do you see any problem on working around the context manager interface this way?

I can't see any problems occurring with usage outside of a context manager. The context manager simply provides a more convenient interface for handling exit / error state. What you have there is essentially the same as what the context manager will be doing (minus the missing rollback bug) and I can't foresee the actual interface, `tx.start()`, `tx.commit()` and `tx.rollback()` changing anytime soon.

**Comment by danigosa** [comment]
Thanks for the feedback! 

The main reason we work around the context manager is because it wasn't calling rollback, I think that if this issue is addressed it can be re-written as simply:

```python
async def db_tx_middleware(request: Request, call_next: Any) -> Response:
    """
    Middleware that creates a transaction per request/response cycle
    Every transaction is either commited or rollback on success/exception
    It stores state on `request.state` context store
    WIP: Preview TransactionManager feature in prisma-client-py@wip/transactions
    """
    response = Response("Internal server error", status_code=500)

    async with prisma.tx() as tx:
          request.state.db = tx
          response = await call_next(request)

    return response
```

And deletegate error handling upstream in the middleware chain.

**Comment by RobertCraigie** [comment]
@caelx Unfortunately not. I will be working on this soon though as it is by far the most requested feature so far.
