### ISSUE TITLE
Invalid code is generated for models with reserved names

### ISSUE THREAD

**Issue by joezhoujinjing** [RobertCraigie/prisma-client-py#594]
## How to reproduce
A database with class as the field will have this bug.

## Prisma information

```prisma
model Class {
  classID      Int         @id @default(autoincrement())
  indicationID Int?
  title        String?     @db.VarChar(512)
  orderID      Int?
  content      String?     @db.Text
  createdAt    DateTime    @db.Timestamp(0)
  updatedAt    DateTime    @db.Timestamp(0)
  Indication   Indication? @relation(fields: [indicationID], references: [indicationID], onDelete: NoAction, onUpdate: NoAction, map: "Class_ibfk_1")
  Progress     Progress[]

  @@index([indicationID], map: "indicationID")
}
```

## Environment & setup

- OS: 
- Database: 
- Python version: 
- Prisma version:

```

```

**Comment by RobertCraigie** [comment]
Hey @joezhoujinjing, could you please provide more information. What does your Prisma Schema file look like?

**Comment by joezhoujinjing** [comment]
For example:

<img width="617" alt="Screenshot 2022-11-17 at 6 28 22 PM" src="https://user-images.githubusercontent.com/10328841/202602950-65fa2286-ecb9-4475-a875-098f2d5bd6a8.png">

**Comment by RobertCraigie** [comment]
Oh I see thank you! From the original issue I didn't understand that you meant literally using the name `class` for a model.

**Comment by RobertCraigie** [comment]
@joezhoujinjing I've put validation in place so that you cannot define a model that will result in this form of error.

To rename your model on the client level you can use `@@map`, see https://www.prisma.io/docs/concepts/components/prisma-schema/data-model#mapping-model-names-to-tables-or-collections for more details.

**Comment by joezhoujinjing** [comment]
I see! So the solution is to validate it. I pulled the schema from an existing database. I guess I will have to change the database in order to use this library?

**Comment by RobertCraigie** [comment]
@joezhoujinjing no you don't have to change it at all!

You can use `@@map` in your Prisma Schema to rename the model at the Prisma level.

**Comment by joezhoujinjing** [comment]
Yes, I figured that out, thanks a lot! Your response is very timely and useful. Kudos!

**Comment by RobertCraigie** [comment]
Happy to help!
