### ISSUE TITLE
Running any command will lead to an error

### ISSUE THREAD

**Issue by De-y** [RobertCraigie/prisma-client-py#665]
## Bug description

Running any command with prisma-client-py (will be abbreviated as prisma to make sense in this report) will not work, even using a virtual environment to install prisma & then running the command from there will not work either. It always leads to the output being an assertion error, where the 'bin' directory does not exist.

## How to reproduce

1. Make a python virtual environment
3. Enter the virtual environment & install the latest version of prisma client.
4. Run any prisma command while in the virtual environment
5. See error

## Expected behavior

Should be able to show the output of the command being used. For example, being able to migrate my schema to my database & being able to show the usable commands when running prisma.

## Prisma information

No information required.

## Environment & setup

- OS: Windows
- Database: Postgres
- Python version: 3.10
- Prisma version: 0.80

```

```

**Comment by RobertCraigie** [comment]
@De-y I can't reproduce this on MacOS, can you share the full stack trace please?

My steps:
- `python3 -m venv .venv`
- `source .venv/bin/activate`
- `pip install -U prisma`
- `prisma version`

**Comment by RobertCraigie** [comment]
It's also worth noting that the `prisma-client-py` command itself is intended to be internal only and will raise an error if used in the wrong context, e.g.

```
$ prisma-client-py
This command is only intended to be invoked internally. Please run the following instead:
prisma <command>
e.g.
prisma generate
```

For normal usage you should use `prisma` or `python -m prisma`.

**Comment by De-y** [comment]
> From what I am getting with the latest version, whenever I run any command, which includes the init command or the migrate dev command, apart from the `prisma` command. I keep receiving this error message:

` 
Installing Prisma CLI
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\accur\Documents\GitHub\app\venv\Scripts\prisma.exe\__main__.py", line 7, in <module>
  File "C:\Users\accur\Documents\GitHub\app\venv\lib\site-packages\prisma\cli\cli.py", line 39, in main
    sys.exit(prisma.run(args[1:]))
  File "C:\Users\accur\Documents\GitHub\app\venv\lib\site-packages\prisma\cli\prisma.py", line 36, in run
    entrypoint = ensure_cached().entrypoint
  File "C:\Users\accur\Documents\GitHub\app\venv\lib\site-packages\prisma\cli\prisma.py", line 91, in ensure_cached
    proc = npm.run(
  File "C:\Users\accur\Documents\GitHub\app\venv\lib\site-packages\prisma\cli\_node.py", line 78, in run
    env=_update_path_env(
  File "C:\Users\accur\Documents\GitHub\app\venv\lib\site-packages\prisma\cli\_node.py", line 293, in _update_path_env
    assert target_bin.exists(), 'Target `bin` directory does not exist'
AssertionError: Target `bin` directory does not exist`

However, when I use version 7.1, it all works fine, giving me the expected functionality.

**Comment by RobertCraigie** [comment]
Thanks for sharing the stack trace :)

Looks like this is an issue with our node resolver, do you have Node installed globally on your machine?

It also probably would be helpful to run the CLI in debug mode: https://prisma-client-py.readthedocs.io/en/stable/reference/logging/#debugging-the-cli

**Comment by De-y** [comment]
I actually didn't have node installed on my machine. I thought it was not needed, but it does work now with node being installed globally.  Thanks!

**Comment by RobertCraigie** [comment]
Glad that fixed it!

It is definitely not needed though, you shouldn't need Node installed on your machine, there is a bug somewhere...

I'll try to look into this on my windows machine as soon as possible.

**Comment by De-y** [comment]
Alright.

**Comment by RobertCraigie** [comment]
@De-y I cannot reproduce this on my windows machine unfortunately...

Even with Node not installed, it works fine.

Could you please set this config option https://prisma-client-py.readthedocs.io/en/latest/reference/config/#use-global-node to `false` and share the debug logs please?

**Comment by De-y** [comment]
Strange, Its working now without node being installed when I am on my wireguard location. Could be my home network. Thanks for helping me out though!

**Comment by RobertCraigie** [comment]
Very strange!

Glad it worked for you in the end. Let me know if you run into it again :)

**Comment by De-y** [comment]
> Very strange!
> 
> Glad it worked for you in the end. Let me know if you run into it again :)

I'm actually running into it again, this time, actually being on my wireguard location & without nodejs being installed. It leads to the same issue.
