### ISSUE TITLE
Support multiple schemas

### ISSUE THREAD

**Issue by De-y** [RobertCraigie/prisma-client-py#666]
## Problem

I am going creating multiple services that will be using multiple prisma schemas interacting with the same database, when I heard about it being in the main prisma client, I thought it would be here, but to my surprise, it isn't actually supported here.
## Suggested solution

I would like to ask if it was possible for the multiple schemas feature to be added, like from the issue on the main prisma client, where they added it as a preview feature.

## Alternatives

I've considered creating a python script that would send over all the login information of the user to the other databases, but it wouldn't work because of the amount of resources it would take for me to do a keep alive request.

## Additional Resources

https://www.prisma.io/docs/guides/database/multi-schema
https://github.com/prisma/prisma/issues/1122

**Comment by RobertCraigie** [comment]
@De-y what parts didn't work for you?

I haven't been able to test this particular feature yet & haven't looked at how it needs to be implemented internally but I'd have thought that  it wouldn't need any changes in the Python client.

Any details about issues you ran into would be incredibly helpful!

**Comment by De-y** [comment]
> @De-y what parts didn't work for you?
> 

> I haven't been able to test this particular feature yet & haven't looked at how it needs to be implemented internally but I'd have thought that it wouldn't need any changes in the Python client.
> 
> Any details about issues you ran into would be incredibly helpful!

It says in the prisma docs for this that it should work like this:
![image](https://user-images.githubusercontent.com/61808223/211127734-06084962-86ef-4897-a873-298276e85c54.png)

But when I follow the method it states to add it, like so:
![image](https://user-images.githubusercontent.com/61808223/211127750-7c02ae00-188d-47e8-9175-8b08cc9d37d7.png)

It leads to me getting the following issue, with multi-schema not being found:
![image](https://user-images.githubusercontent.com/61808223/211127818-dfe2f1cf-0072-4da6-bb51-561361b24e3e.png)

Do you know what I could do to fix this with my main schema before I move on to the other schemas?

**Comment by RobertCraigie** [comment]
Huh that's strange, you're on the latest version of Prisma Client Python?

**Comment by De-y** [comment]
> Huh that's strange, you're on the latest version of Prisma Client Python?

Yep.

**Comment by RobertCraigie** [comment]
@De-y This generated correctly for me:

```prisma
datasource db {
  provider = "postgresql"
  url      = env("POSTGRESQL_URL")
  schemas  = ["base", "transactional"]
}

generator client {
  provider             = "prisma-client-py"
  interface            = "asyncio"
  recursive_type_depth = -1
  previewFeatures      = ["multiSchema"]
  enable_experimental_decimal = true
}
```

What does `prisma version` output for you?

```
$ prisma version
prisma                : 4.8.0
@prisma/client        : Not found
Current platform      : darwin-arm64
Query Engine (Binary) : query-engine d6e67a83f971b175a593ccc12e15c4a757f93ffe (at ../../.cache/prisma-python/binaries/4.8.0/d6e67a83f971b175a593ccc12e15c4a757f93ffe/node_modules/@prisma/engines/query-engine-darwin-arm64)
Migration Engine      : migration-engine-cli d6e67a83f971b175a593ccc12e15c4a757f93ffe (at ../../.cache/prisma-python/binaries/4.8.0/d6e67a83f971b175a593ccc12e15c4a757f93ffe/node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine  : introspection-core d6e67a83f971b175a593ccc12e15c4a757f93ffe (at ../../.cache/prisma-python/binaries/4.8.0/d6e67a83f971b175a593ccc12e15c4a757f93ffe/node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary         : prisma-fmt d6e67a83f971b175a593ccc12e15c4a757f93ffe (at ../../.cache/prisma-python/binaries/4.8.0/d6e67a83f971b175a593ccc12e15c4a757f93ffe/node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Format Wasm           : @prisma/prisma-fmt-wasm 4.8.0-61.d6e67a83f971b175a593ccc12e15c4a757f93ffe
Default Engines Hash  : d6e67a83f971b175a593ccc12e15c4a757f93ffe
Studio                : 0.479.0
```

(Note that I haven't tested runtime behaviour of `multiSchema` yet)

**Comment by De-y** [comment]
I don't know what is happening anymore with prisma, when I have it installed & try to run any command, it leads to the following traceback:

```
Installing Prisma CLI
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\accur\Documents\GitHub\app\venv\Scripts\prisma.exe\__main__.py", line 7, in <module>
  File "C:\Users\accur\Documents\GitHub\app\venv\lib\site-packages\prisma\cli\cli.py", line 39, in main
    sys.exit(prisma.run(args[1:]))
  File "C:\Users\accur\Documents\GitHub\app\venv\lib\site-packages\prisma\cli\prisma.py", line 36, in run
    entrypoint = ensure_cached().entrypoint
  File "C:\Users\accur\Documents\GitHub\app\venv\lib\site-packages\prisma\cli\prisma.py", line 91, in ensure_cached
    proc = npm.run(
  File "C:\Users\accur\Documents\GitHub\app\venv\lib\site-packages\prisma\cli\_node.py", line 78, in run
    env=_update_path_env(
  File "C:\Users\accur\Documents\GitHub\app\venv\lib\site-packages\prisma\cli\_node.py", line 293, in _update_path_env
    assert target_bin.exists(), 'Target `bin` directory does not exist'
AssertionError: Target `bin` directory does not exist
```

The problem is, I also have nodejs installed & have no idea what is going wrong here, I even uninstalled & reinstalled prisma, destroyed & created the venv again, but it is to no avail.

**Comment by De-y** [comment]
Okay. This is even stranger for me, I had to install the regular prisma client version & then generate with that to make my copy of prisma-client-py to even work. I don't even know how it works, but it did.

**Comment by kivo360** [comment]
It's probably the binary.
