### ISSUE TITLE
Limiting generators not working as documented (--generators=), but --generator does work

### ISSUE THREAD

**Issue by gjmoed** [RobertCraigie/prisma-client-py#700]
Just a quick note, as the topic mentions, the new feature for using a specific generator, doesn't work as documented for this new release 0.8.1. It says to use the --generators= syntax, which doesn't match the official Prisma docs either btw. Using something like `prisma generate --generator python` does work. Awesome work btw, and awesome new feature as well.

**Comment by RobertCraigie** [comment]
Ah thank you for catching this! I've fixed the typo in the release notes.
