### ISSUE TITLE
Add fail-safe for downloading binaries.

### ISSUE THREAD

**Issue by De-y** [RobertCraigie/prisma-client-py#705]
## Problem

Whenever I wish to run the prisma command after installation, it will download binaries. Whenever I CTRL+C the task through the download process. It will cause me to not be able to download the binaries in the future unless there is a new update OR if I install NodeJS. It always frustrates me whenever this happens, so I have to wait till it does install in the future.

## Suggested solution

I suggest adding a fail-safe for the downloading binaries, as if it is cancelled whilst the binaries are being downloaded, it will lead to the issue that the binaries haven't been downloaded.

## Alternatives

I haven't currently considered anything else, sorry!

## Additional context

Issue #665.

**Comment by RobertCraigie** [comment]
@De-y If I'm understanding correctly, you're saying that if you interrupt the CLI during the install process at a certain point, it will think the binaries are downloaded when they in fact are not?

**Comment by De-y** [comment]
Yep!

**Comment by RobertCraigie** [comment]
@De-y If you're interested I have a PR that attempts to fix this but I haven't been able to reproduce your exact problem yet. If you have time to try it out and let me know if it fixes the issue for you it would be greatly appreciated :)

https://github.com/RobertCraigie/prisma-client-py/pull/708

**Comment by RobertCraigie** [comment]
Hey @De-y, I haven't confirmed that my changes did fix your issue but I wanted to merge them in so that they're included in the next release. Please let me know if you are still running into it!

**Comment by De-y** [comment]
I am no longer running into this problem, thanks for asking!

**Comment by RobertCraigie** [comment]
Amazing!

**Comment by Oblynx** [comment]
I ran into the error `AssertionError: Target `bin` directory does not exist` and I think that the installation was interrupted. The problem remained when I ran `prisma generate` again. I then deleted my container and ran `prisma generate` in the new environment and it worked.

So I think I ran into this issue again. Using prisma-python v0.9.
