### ISSUE TITLE
Support Prisma TS's `findUniqueOrThrow`

### ISSUE THREAD

**Issue by defrex** [RobertCraigie/prisma-client-py#719]
## Problem

Often when fetching a model by ID I expect the result not to be `None`. If for some reason it is, an error should be raised, rather than always returning an optional type which needs a manual guard.

## Suggested solution

Follow the pattern from the TypeScript client, add `find_unique_or_raise` and `find_first_or_raise` methods.

https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#finduniqueorthrow

## Alternatives

A previous version of the TS client used an  argument `findUnique({ throwOnNotFound: true })`, which also solved the problem just fine. I'm not sure why they decided to deprecate that and make the switch to dedicated methods.

**Comment by RobertCraigie** [comment]
Also see discussion in the discord: https://discord.com/channels/933860922039099444/933860923117043718/1082710175049322697

I'm leaning towards `find_$_or_raise` as well.
