### ISSUE TITLE
Exception: TypeError: Object of type 'x' is not JSON serializable

### ISSUE THREAD

**Issue by danielweil** [RobertCraigie/prisma-client-py#73]
Hello Again!

How should we return this in the API response? I tried using json.dumps and got that my object is not JSON Serializable.

Any solutions regarding this issue?

Thanks!

**Comment by RobertCraigie** [comment]
Can you show me the code you're using please?

If 'x' is a pydantic model then you should use `x.json`.

**Comment by danielweil** [comment]
In my case it was a find_many clause. Got it to work like this:

`async def get_handler(req: func.HttpRequest) -> func.HttpResponse:
    logging.info('Python HTTP trigger function processed a request.')

    client = Client()
    await client.connect()

    submissions = await client.submission.find_many()
    await client.disconnect()
    
    json_submissions = [*map(lambda x: x.json(), submissions)]
    
    return func.HttpResponse(json.dumps(json_submissions), headers={"content-type": "application/json"})`


Is this ok?

**Comment by RobertCraigie** [comment]
Yeah that seems good.

I don't think the lambda is necessary though, could probably be rewritten as:

```py
json_submissions = [x.json() for x in submissions]
`|`

**Comment by danielweil** [comment]
Thanks for the help!
