### ISSUE TITLE
Field name "from" shadows a Python keyword

### ISSUE THREAD

**Issue by Kaszanas** [RobertCraigie/prisma-client-py#764]
## Bug description

Unable to run ```prisma generate``` with python client after ```prisma db pull``` after installing prisma through pip.

## How to reproduce

Run the following commands for existing Postgres database:
1. Run ```prisma init``` (by default the generator is set to ```prisma-client-js```) (and generating a JS client works after ```prisma db pull```)

```
✔ Your Prisma schema was created at prisma/schema.prisma
  You can now open it in your favorite editor.

warn Prisma would have added DATABASE_URL but it already exists in .env

Next steps:
1. Set the DATABASE_URL in the .env file to point to your existing database. If your database has no tables yet, read https://pris.ly/d/getting-started
2. Set the provider of the datasource block in schema.prisma to match your database: postgresql, mysql, sqlite, sqlserver, mongodb or cockroachdb.
5. Run prisma db pull to turn your database schema into a Prisma schema.
6. Run prisma generate to generate the Prisma Client. You can then start querying your database.
More information in our documentation:
https://pris.ly/d/getting-started
```

2. Run ```prisma db pull```
4. Follow the steps as suggested by the command line:

5. Change ```prisma-client-js``` to ```prisma-client-py```
6. Run ```prisma generate```, and get the following errors:

```
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma

Some types are disabled by default due to being incompatible with Mypy, it is highly recommended
to use Pyright instead and configure Prisma Python to use recursive types. To re-enable certain types:

generator client {
  provider             = "prisma-client-py"
  recursive_type_depth = -1
}

If you need to use Mypy, you can also disable this message by explicitly setting the default value:

generator client {
  provider             = "prisma-client-py"
  recursive_type_depth = 5
}

For more information see: https://prisma-client-py.readthedocs.io/en/stable/reference/limitations/#default-type-limitations

Error:
dmmf -> datamodel -> models -> 22 -> fields -> 23 -> type
  Support for the Decimal type is experimental
  As such you must set the `enable_experimental_decimal` config flag to true
  for more information see: https://github.com/RobertCraigie/prisma-client-py/issues/106 (type=value_error) 
```

7. Apply the suggested change by the issue.
8. Rerun the command ```prisma generate```, and get the following errors:

```
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Error:
2 validation errors for PythonData
dmmf -> datamodel -> models -> 12 -> fields -> 5 -> name
  Field name "from" shadows a Python keyword; use a different field name with '@map("from")'. (type=value_error)  
dmmf -> datamodel -> models -> 31 -> fields -> 7 -> name
  Field name "from" shadows a Python keyword; use a different field name with '@map("from")'. (type=value_error)
```
9. Try to adjust the ```prisma.schema``` manually according to this: https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/use-custom-model-and-field-names by using the ```@map()```
10. Rerun and get the same message.

## Expected behavior

Generated Python prisma client for interfacing with the database.

## Prisma information

Example before change:

```prisma
model ExampleModel {
  from          String?         @db.VarChar(255)
}
```

Example after change:

```prisma
model ExampleModel {
  from          String?         @db.VarChar(255) @map("from_str")
}
```

## Environment & setup

- OS: Windows
- Database: Postgres
- Python version: 3.11.0
- Prisma version: 4.11.0

```
prisma                  : 4.11.0
prisma client python    : 0.8.2
platform                : windows
expected engine version : 8fde8fef4033376662cad983758335009d522acb
installed extras        : []
install path            : D:\SomeProject\venv\Lib\site-packages\prisma
binary cache dir        : C:\SomePath\.cache\prisma-python\binaries\4.11.0\8fde8fef4033376662cad983758335009d522acb
```

**Comment by RobertCraigie** [comment]
Hey @Kaszanas, it looks like you've misunderstood how `@map` works. The value you pass corresponds to the database column name, not the name in the Prisma Client.

For example:
```prisma
model ExampleModel {
  from_str          String?         @db.VarChar(255) @map("from")
}
```

With this schema, your original database schema is preserved and the client will use `from_str`.

It should be noted that I also thought that it worked the same way you did when I originally discovered `@map`, I'll see if there's been any discussion about this name being ambiguous.

**Comment by Kaszanas** [comment]
Thank you @RobertCraigie apparently I was not able to find suitable information on this error elsewhere online. I have successfully generated the Python client.
