### ISSUE TITLE
Allow specifying generated package name and location

### ISSUE THREAD

**Issue by danielgafni** [RobertCraigie/prisma-client-py#860]
## Problem

It seems like currently there is no way of doing this. The generated code is always placed in the available `side-packages` directory. This makes it impossible (or very hard) to distribute a package which depends on a `prisma` client, because (1) the generated code is outside of the package and (2) it always has the `prisma` name, which causes a name clash if more than package in the virtual environment is using `prisma` client. 
## Suggested solution

For the `prisma generate` CLI command:

1. Allow specifying `--target-path` (or similar) argument for generated code location (default `None` which corresponds to current venv `site-packages`)
2. Allow specifying `--package-name` (default `prisma`) 

## Additional context

I am considering to use `prisma` for a CLI application which is using an external DB. The app is distributed as an internal Python package (installable via `pip`, `poetry`, etc from a private PyPI server). However, it's not clear to me how do I properly package the generated client code with the app.

**Comment by RobertCraigie** [comment]
Hey @danielgafni, sorry I don't think the docs cover this properly yet. You can achieve this using the `output` property in your `schema.prisma` file, https://www.prisma.io/docs/orm/reference/prisma-schema-reference#specify-a-custom-output-location-for-prisma-client.
