### ISSUE TITLE
How to import enum values by prisma-client-py ?

### ISSUE THREAD

**Issue by hanamurayuki** [RobertCraigie/prisma-client-py#861]
## Question
```python
# schema.prisma
enum Role {
  ADMIN
  GUEST
}

model Member {
  id   String @id @default(uuid())
  role Role       @default(GUEST)
  name String
  ...
```
In official version (typescript), I can read enum values from schema.prisma.
`import { Role } from "@prisma/client"`
`console.log(Role.GUEST)` -> "GUEST"

But, in prisma-client-py, 
how can I import enum values from schema.prisma ?

I tried, but it doesn't work.
```python
prisma = Prisma()
await self.prisma.connect()
print(prisma.Role)
-> `AttributeError: 'Prisma' object has no attribute 'Role'`
```

**Comment by RobertCraigie** [comment]
@hanamurayuki Enums are generated to the `prisma.enums` module, e.g.

``py
from prisma.enums import Role
```
