### ISSUE TITLE
Once event loop is closed, async client can not be used anymore.

### ISSUE THREAD

**Issue by Gnosnay** [RobertCraigie/prisma-client-py#888]
## Bug description

Once event loop is closed, async client can not be used anymore.

## How to reproduce

I am working on one fast api project. Because i found the prisma client can only be register once, i used the function like

```
async def get_async_db_session() -> AsyncPrisma:
    try:
        db = get_async_client()
    except AsyncClientNotRegisteredError:
        db = AsyncPrisma(
            auto_register=True, datasource={"url": str(settings.MYSQL_DSN)}
        )
    if not db.is_connected():
        await db.connect()
    return db
```

to get the global client.

Problems happened when I writes test cases. I have two types of test cases, one is synced another one is asynced.

synced testcase will be executed firstly, which will call function above function. I found the this test case finished, the event loop will be closed.

so when asynced testcases are executed, prisma will raise one exception said `Event loop is closed`.

## Expected behavior

Whether we can re-register the global prisma?

## Prisma information

```prisma

```

## Environment & setup

- OS: 
- Database: 
- Python version: 
- Prisma version:

```

```

**Comment by Gnosnay** [comment]
i understand that i should keep the event loop active during the test.

I just worry about that what if we are in production, and eventloop is closed..

**Comment by RobertCraigie** [comment]
@Gnosnay In production, the event loop should stay open the entire time as well. Are there specific cases that you're concerned about?

The reason pytest-asyncio closes the event loop after each test is to avoid the potential leaking of any tasks or other async things across tests, it's not representative of a typical production experience in that way.
