### ISSUE TITLE
Add support for batching queries

### ISSUE THREAD

**Issue by RobertCraigie** [RobertCraigie/prisma-client-py#9]
## Problem

In some situations it is desirable that a write operation being committed is dependant on other write operations succeeding, for example, if you update 200 users within a transaction, each update must succeed - if not, all changes are rolled back and the transaction fails as a whole.

## Suggested solution

> We cannot support the same syntax that prisma [does](https://www.prisma.io/docs/concepts/components/prisma-client/transactions#the-transaction-api) as we need to support a synchronous API as well

This is a good solution as it can easily be modified to support dependencies between write operations if it is added to the prisma query engine, [#1844](https://github.com/prisma/prisma/issues/1844).

The only potential problem with this solution is that we are creating a new client reference which would potential be difficult for some users to implement but I cannot think of a way to do this while maintaining type safety.

`async`
```py
async with client.batch_() as tx:
    tx.user.create({'name': 'Robert'})
    tx.user.create({'name': 'Bob'})

tx = client.batch_()
tx.user.create({'name': 'Robert'})
tx.user.create({'name': 'Bob'})
await tx.commit()
```

`sync`
```py
with client.batch_() as tx:
    tx.user.create({'name': 'Robert'})
    tx.user.create({'name': 'Bob'})

tx = client.batch_()
tx.user.create({'name': 'Robert'})
tx.user.create({'name': 'Bob'})
tx.commit()
```

## Additional context

* [https://www.prisma.io/docs/guides/prisma-guides/prisma-client-transactions-guide](https://www.prisma.io/docs/guides/prisma-guides/prisma-client-transactions-guide)
* [https://www.prisma.io/docs/concepts/components/prisma-client/transactions#the-transaction-api](https://www.prisma.io/docs/concepts/components/prisma-client/transactions#the-transaction-api)

## Implementation notes

As we have to type every action to return None there will be some refactoring to support it, but it should be possible with generics and if not we can always duplicate the whole client/actions classes with Jinja

**Comment by danielweil** [comment]
Can this be used to copy the behaviour seen in this part of the doc? https://www.prisma.io/docs/guides/performance-and-optimization/prisma-client-transactions-guide#interactive-transactions-in-preview

I need to create an object in the database, and if it gives me an error in the function executed next, the changes should be rollbacked...

**Comment by RobertCraigie** [comment]
@danielweil ah that is a different feature, see #53.

Query batching is only used when you want to send a lot of queries at once without having access to the returned objects, e.g. if you're moving data from a JSON file to a Prisma model.
