### ISSUE TITLE
Define connection string when calling Client

### ISSUE THREAD

**Issue by danielweil** [RobertCraigie/prisma-client-py#92]
I am trying to connect to PostgreSQL database with Azure AD credentials, and it requires me to connect with JWT Access Token. To do it, I was trying to set the connection string when calling the client object as told possible and specified in this issue https://github.com/prisma/prisma/issues/2443#issuecomment-630679118. 

Can we have it implemented in the python client as well? I tried the same and it gave me a "Exception: NameError: name 'datasources' is not defined".

Faithfully,

**Comment by RobertCraigie** [comment]
@danielweil Could you share the full traceback please?

**Comment by RobertCraigie** [comment]
Dynamically overriding the datasource is supported by the python client.

```py
other = Client(
    datasource={'url': 'file:./tmp.db'},
)
```

**Comment by danielweil** [comment]
Thanks!
