### ISSUE TITLE
Oracle Database not support like alchemy

### ISSUE THREAD

**Issue by raibann** [RobertCraigie/prisma-client-py#935]
Supported database providers:
PostgreSQL
MySQL
SQLite
CockroachDB
MongoDB (experimental)
SQL Server (experimental)
Oracle (Not support)

**Comment by RobertCraigie** [comment]
Hey @raibann, Oracle DB is not supported by Prisma in general which is a pre-requisite for supporting it in the Python Client. See this issue: https://github.com/prisma/prisma/issues/2853
