### ISSUE TITLE
Bump Prisma version to latest 5.12.1

### ISSUE THREAD

**Issue by gauranshkumar** [RobertCraigie/prisma-client-py#941]
## Bug description
The latest Prisma 5.12.1 now supports `create_many()` method https://github.com/prisma/prisma/issues/10710#issuecomment-2034531710 

Please update the underlying version as soon as possible. Thanks!

**Comment by RobertCraigie** [comment]
`v0.14.0` has been released which bumps the prisma version to `v5.17.0`!
