### ISSUE TITLE
Import generated types

### ISSUE THREAD

**Issue by owencraston** [RobertCraigie/prisma-client-py#975]
## Problem

I keep creating models that represent the data in my schema.prisma. I know that prisma python client has generated these types since I see them in the type errors. Is there a way for me to easily import these generated types into my codebase?

## Suggested solution

Similar to how the typescript client works, it would be great to be able to import the types from the python client.

EX:

```ts
import {
  Education,
  Gender,
  SalaryRange,
} from "@prisma/client";
```

**Comment by RobertCraigie** [comment]
You can import them from `prisma.types`, `prisma.models` & `prisma.enums`.
