### ISSUE TITLE
Select specific columns on find_many

### ISSUE THREAD

**Issue by Saya47** [RobertCraigie/prisma-client-py#990]
Firstly, I'd like to thank you for this beautiful work, well done.

## Problem

In Prisma we can select specific column in the find queries, I wish to have the same feature in Python: https://www.prisma.io/docs/orm/prisma-client/queries/select-fields

## Suggested solution

Add `select` parameter to `find_many`.

## Alternatives

None

## Additional context

None

Thanks a lot for your time.

**Comment by RobertCraigie** [comment]
Please see https://github.com/RobertCraigie/prisma-client-py/issues/960, there is already support for this feature but it isn't as ergonomic as I'd like yet.
