### ISSUE TITLE
[Question] Should prisma use http_proxy env var to connect to database

### ISSUE THREAD

**Issue by Saya47** [RobertCraigie/prisma-client-py#991]
Greetings,

Should Python Prisma client use http_proxy env var to connect to the database? It does and I think it really should not!

Thanks for your time!

**Comment by RobertCraigie** [comment]
The python client doesn't have any specific handling of http proxies, so this behaviour is coming from the core prisma internals and will be the same in the JS client. Please ask this question in the https://github.com/prisma/prisma repi
