### ISSUE TITLE
Deserialization does not respect optional fields for special types for raw queries

### ISSUE THREAD

**Issue by AstreaTSS** [RobertCraigie/prisma-client-py#998]
## Bug description

If a field can be null/`None` and is specially handled with the `DESERIALIZERS` variable found in `prisma/_raw_query` (ie BigInt, Decimal, Json), then any raw queries which has said field and is null will error out.

This only happens on 0.14.0 and above, as raw queries were reworked for that version.

## How to reproduce

1. Define a schema with an optional BigInt/Decimal/Json value:
```prisma
model PrismaBugExample {
  id          Int      @id @default(autoincrement())
  bad_var     BigInt?
}
```
2. Set up the tables and your Python program, and create an entry with a null/`None` value for `bad_var`:
```python
await PrismaBugExample.prisma().create(data={"bad_var": None})
```
3. Make a raw query getting that entry:
```python
data = await PrismaBugExample.prisma().query_first("SELECT * FROM PrismaBugExample")
```
The bug should occur at this step.

## Expected behavior

For raw queries including these nullable types to work.

## Prisma information

Schema: https://github.com/AstreaTSS/PYTHIA/blob/8873fd94c770c9faa503c70201c01af3a0390943/schema.prisma
Models (there is some post-generation adjustments that I do to them - it has no affect on this bug but I might as well include everything): https://github.com/AstreaTSS/PYTHIA/blob/8873fd94c770c9faa503c70201c01af3a0390943/common/models.py
Query:
- Actual Query: https://github.com/AstreaTSS/PYTHIA/blob/8873fd94c770c9faa503c70201c01af3a0390943/common/models.py#L434-L452 
- Execution: https://github.com/AstreaTSS/PYTHIA/blob/8873fd94c770c9faa503c70201c01af3a0390943/common/models.py#L122-L124

```prisma

```

## Environment & setup

- OS: Windws
- Database: PostgreSQL
- Python version: 3.12.3
- Prisma version:

```
prisma                  : 5.17.0
prisma client python    : 0.14.0
platform                : debian-openssl-1.1.x
expected engine version : 393aa359c9ad4a4bb28630fb5613f9c281cde053
installed extras        : []
install path            : /home/astrea/Documents/PYTHIA/env/lib/python3.12/site-packages/prisma
binary cache dir        : /home/astrea/.cache/prisma-python/binaries/5.17.0/393aa359c9ad4a4bb28630fb5613f9c281cde053
```

## Internal cause

Doing some investigation on my own, I found the culprit of the bug - `_deserialize_prisma_object` in `src/prisma/_raw_query.py`:
https://github.com/RobertCraigie/prisma-client-py/blob/f1ab3b183cbfaf2d0c7c0c9bce0aeec346236841/src/prisma/_raw_query.py#L122-L166

More specifically, focusing in on the non-array handling (essentially [a single line](https://github.com/RobertCraigie/prisma-client-py/blob/f1ab3b183cbfaf2d0c7c0c9bce0aeec346236841/src/prisma/_raw_query.py#L161)), we get this:
```python
new_obj[key] = _deserializers[prisma_type](value, for_model) if prisma_type in _deserializers else value
```

From my understanding, what this does is:
- Sees if the `prisma_type` (which I think is gathered from the model or from Prisma proper - point is, it's gotten independently of the actual query result) is in the `DESERIALIZERS` mentioned earlier (though aliased under `_deserializers`).
- If it is, then it throws the gotten value directly into the deserializer.

Note that this makes *no* check to see if the value is, say, `None`. Interestingly enough, [arrays do check for `None`](https://github.com/RobertCraigie/prisma-client-py/blob/f1ab3b183cbfaf2d0c7c0c9bce0aeec346236841/src/prisma/_raw_query.py#L139-L142), meaning it won't occur there.

Anyways, a potential fix is just to hoist that `None` check for arrays to above the conditional statement, making it run for all values regardless of type. I was unsure if that fixes the issue in every case, and I'm unsure if that's necessarily the way it should be fixed, hence this issue.

**Comment by RobertCraigie** [comment]
Thanks for the detailed bug report, I agree with your suggested fix. The `None` check should be hoisted.
